### ISSUE TITLE
running_time() doesn't seem to work

### ISSUE THREAD

**Issue by eldog** [ntoll/upyed#3]
Hi,

I'm doing something like this

```
import microbit

now = running_time()

microbit.display.scroll("%d" % now)
```

But it errors and scrolls out "line 3".

It's working in the microrepl, I guess the .hex needs updating?

Thanks,

Lloyd

**Comment by ntoll** [comment]
Odd. It works for me.

Here's what I'd do:
- pip install uflash
- Connect your device and type `uflash` to flash it with a "vanilla" version of a recent build of MicroPython.
- Connect to the REPL
- Tell me what you get.

Also, in the REPL mode, you don't have to import microbit, we've already done the equivalent of `from microbit import *`

**Comment by eldog** [comment]
Thanks for the reply.

Yes you're right. I was using the upyed editor and thought that `running_time()` was in the global scope from when I was using the REPL.

This works as expected.

```
import microbit

now = microbit.running_time()

microbit.display.scroll("%d" % now)
```

**Comment by ntoll** [comment]
A quick heads up, upyed is an evolutionary dead end. The effort is being put into "mu" (https://github.com/ntoll/mu). Best bet is to clone the repository and have a play. :-)

**Comment by eldog** [comment]
Wow mu solves all the annoying problems of microbit dev! Thanks for the work/tip.
